Repository sociomantic-tsunami/ocean, pull requests merged in 2018-05, with the labels that each got.

#508 Add note about the delay in handling the signal using SignalExt
  src/ocean/util/app/DaemonApp.d
  src/ocean/util/app/ext/SignalExt.d
Labels: type-enhancement

#505 Specify exact d1to2fix version to use
  docker/build
Labels: part-infrastructure, type-bug

#501 Increase Application own order among extensions
  relnotes/order.feature.md
  src/ocean/util/app/ext/RefuseRootExt.d
  src/ocean/util/app/ext/ReopenableFilesExt.d
  src/ocean/util/app/ext/TaskExt.d
  src/ocean/util/app/ext/TimerExt.d
  src/ocean/util/app/ext/UnixSocketExt.d
Labels: type-bug, type-enhancement

#520 Fix performance regression in task timer utils
  src/ocean/task/util/Timer.d
Labels: type-bug
