Repository sociomantic-tsunami/ocean, pull requests merged in 2018-10, with the labels that each got.

#641 Enable stomping for suspendables array
  src/ocean/io/model/ISuspendableThrottler.d
Labels: type-bug

#631 Automatically resume tasks after exception
  relnotes/continuetask.deprecation.md
  src/ocean/task/IScheduler.d
  src/ocean/task/Scheduler_test.d
  src/ocean/task/Task.d
Labels: type-deprecation, type-enhancement

#642 Improve and fix ISuspendableThrottler style
  src/ocean/io/model/ISuspendableThrottler.d
Labels: type-refactoring

#647 Fix equality expression in ocean/core/Traits
  src/ocean/core/Traits.d
Labels: type-bug, type-refactoring

#651 Revert "Add suspendables to throttler in consistent state"
  src/ocean/io/model/ISuspendableThrottler.d
Labels: difficulty-easy, type-bug

#650 Make closures CI script fail for parts of pipeline
  ci/closures.sh
Labels: part-infrastructure, type-bug

#656 Workaround optimizer bug
  src/ocean/math/IEEE.d
Labels: type-bug
