Repository sociomantic-tsunami/ocean, pull requests merged in 2018-08, with the labels that each got.

#607 Fix segfault in AppStatus.num_static_lines when terminal_output is null
  src/ocean/io/console/AppStatus.d
Labels: type-bug

#609 Don't allocate in ProcVFS.getOpenFdCount
  src/ocean/sys/stats/linux/ProcVFS.d
Labels: type-bug

#422 `json.JsonEscape.unescape` throws non-reusable exceptions
  src/ocean/text/json/JsonEscape.d
Labels: type-bug, type-enhancement

#611 Flush BufferedOutput on close
  integrationtest/buffered/main.d
  src/ocean/io/stream/Buffered.d
Labels: type-bug

#614 Move leftover `test` directory
  integrationtest/timerext/main.d
Labels: part-infrastructure, type-bug

#619 Fix broken links in README.rst
  README.rst
Labels: type-bug

#593 `ocean.text.Arguments.getInt()` does not extract specified int type
  src/ocean/text/Arguments.d
Labels: part-app, res-invalid, type-bug

#617 Add statistics counter for generating a time histogram
  relnotes/histogram.feature.md
  src/ocean/math/TimeHistogram.d
Labels: type-feature

#620 Assign elements to a static or dynamic array
  relnotes/array.feature.md
  src/ocean/core/array/Transformation.d
Labels: type-feature

#616 Add ebtree based TreeMap data structure
  relnotes/treemap.feature.md
  src/ocean/util/container/map/TreeMap.d
Labels: type-feature

#388 Validation of overridden config value
  relnotes/cli_override.migration.md
  src/ocean/util/app/ext/ConfigExt.d
Labels: part-app, type-breaking, type-bug
