Repository sociomantic-tsunami/ocean, pull requests merged in 2018-11, with the labels that each got.

#658 Workaround task pool regression from v4.4.0
  src/ocean/task/TaskPool.d
Labels: prio-high, type-bug

#649 Make validateTime and validateDate public
  relnotes/datetime.feature.md
  src/ocean/text/convert/DateTime.d
Labels: type-enhancement

#659 Implement utility for task usage in scripts
  relnotes/quickrun.feature.md
  src/ocean/task/util/QuickRun.d
  src/ocean/task/util/QuickRun_test.d
Labels: part-tasks, type-feature
