Repository sociomantic-tsunami/ocean, pull requests merged in 2018-04, with the labels that each got.

#480 Always use `Exception.message()` instead of `getMsg()`
  integrationtest/httpserver/main.d
  integrationtest/scheduler/main.d
  src/ocean/core/Enforce.d
  src/ocean/core/Exception.d
  src/ocean/core/Test.d
  src/ocean/core/UnitTestRunner.d
  src/ocean/io/FileException.d
  src/ocean/io/select/EpollSelectDispatcher.d
  src/ocean/io/select/client/model/ISelectClient.d
  src/ocean/io/select/protocol/fiber/model/IFiberSelectProtocol.d
  src/ocean/io/select/selector/SelectedKeysHandler.d
  src/ocean/net/http/HttpException.d
  src/ocean/net/server/unix/UnixListener.d
  src/ocean/sys/ErrnoException.d
  src/ocean/sys/Process.d
  src/ocean/sys/Stats.d
  src/ocean/task/Task.d
  src/ocean/text/Text.d
  src/ocean/text/json/JsonExtractor.d
  src/ocean/util/app/Application.d
  src/ocean/util/app/ext/ConfigExt.d
  src/ocean/util/config/ConfigFiller.d
  src/ocean/util/config/ConfigParser.d
  src/ocean/util/container/queue/FlexibleFileQueue.d
  src/ocean/util/container/queue/FlexibleRingQueue.d
  src/ocean/util/serialize/contiguous/Deserializer.d
  src/ocean/util/serialize/contiguous/MultiVersionDecorator.d
Labels: type-refactoring

#478 Add show_version command to the application's control socket
  relnotes/version.feature.md
  src/ocean/util/app/DaemonApp.d
  src/ocean/util/app/ext/VersionArgsExt.d
Labels: type-enhancement

#339 Add formatting helper for SmartUnions
  relnotes/smartunionformatter.feature.md
  src/ocean/core/SmartUnion.d
  src/ocean/text/formatter/SmartUnion.d
Labels: type-feature

#481 Deprecate error aliases
  relnotes/error.deprecation.md
  src/ocean/core/ExceptionDefinitions.d
  src/ocean/core/UnitTestRunner.d
  src/ocean/sys/HomeFolder.d
  src/ocean/util/container/more/Vector.d
Labels: type-deprecation

#482 Add buffer overload to Uri.produce and usage example
  relnotes/uri.feature.md
  src/ocean/net/Uri.d
Labels: type-refactoring
