Repository sociomantic-tsunami/ocean, pull requests merged in 2018-03, with the labels that each got.

#473 Remove meaningless destructor
  src/ocean/io/compress/lzo/LzoChunkCompressor.d
Labels: type-bug

#469 Deprecate old serializer mixins
  Build.mak
  relnotes/serializer.deprecation.md
  src/ocean/util/serialize/contiguous/model/LoadCopyMixin.d
  src/ocean/util/serialize/model/VersionDecoratorMixins.d
Labels: type-deprecation

#474 Throw exception instead of error in ParamSet
  src/ocean/net/util/ParamSet.d
Labels: type-bug, type-d2-migration

#476 Remove unused (and wrong) extern (C) declarations
  src/ocean/io/stream/Buffered.d
  src/ocean/text/convert/Float.d
Labels: type-bug

#477 BufferedInput: Extend the buffer if needed
  relnotes/bufferinput.feature.md
  src/ocean/io/stream/Buffered.d
Labels: prio-high, type-enhancement
