Repository sociomantic-tsunami/ocean, pull requests merged in 2018-07, with the labels that each got.

#543 Do not enable SIGTERM unconditionally
  relnotes/signal.migration.md
  src/ocean/util/app/DaemonApp.d
Labels: type-breaking

#549 Fix multiple shutdown attempt corrupting state
  src/ocean/task/Scheduler.d
Labels: type-bug

#552 Fix startEventHandling verify condition
  src/ocean/util/app/DaemonApp.d
Labels: type-bug

#550 Fix broken shutdown if scheduling from event loop context
  src/ocean/task/Scheduler.d
Labels: prio-high, type-bug

#557 Allow specifying AppStatus heading line components
  relnotes/heading.feature.md
  src/ocean/io/console/AppStatus.d
Labels: type-feature

#558 Bugfix: `FullQueryParamSet.parse` did not add remaining elements.
  src/ocean/net/util/QueryParams.d
Labels: type-bug

#604 Replace dmd-transitional 2.070 with 2.078 in CI
  .travis.yml
Labels: part-infrastructure
