Repository sociomantic-tsunami/ocean, pull requests merged in 2018-12, with the labels that each got.

#666 Implement DynamicQueue
  relnotes/dynamic_queue.feature.md
  src/ocean/util/container/queue/DynamicQueue.d
Labels: type-feature

#664 Add select cycle callbacks to eventLoop
  relnotes/select_cycle_callbacks.md
  src/ocean/io/select/EpollSelectDispatcher.d
Labels: part-tasks, type-enhancement

#663 prepare for precise garbage collection
  src/ocean/util/container/map/model/Bucket.d
Labels: type-refactoring
