Repository sociomantic-tsunami/ocean, pull requests merged in 2018-09, with the labels that each got.

#630 Allow for dynamic terminal width inside AppStatus
  src/ocean/io/console/AppStatus.d
Labels: type-bug

#628 Rename ClassIterator -> ConfigIterator and support struct types.
  relnotes/classiterator.deprecation.md
  relnotes/configfiller.feature.md
  src/ocean/util/config/ConfigFiller.d
Labels: type-deprecation, type-feature

#632 Introduce minimal bindings to OpenSSL
  Build.mak
  relnotes/sslbinding.feature.md
  src/ocean/net/ssl/openssl/OpenSsl.d
Labels: type-enhancement, type-feature

#633 Make use of AppStatus.terminal_columns field
  src/ocean/io/console/AppStatus.d
Labels: type-bug

#636 Add D2-only lvalue support to assumeUnique
  src/ocean/core/TypeConvert.d
Labels: type-enhancement

#629 Add stats log reader
  relnotes/StatsLogReader.feature.md
  src/ocean/util/log/StatsReader.d
Labels: type-enhancement, type-feature

#637 Stop printing at \0
  src/ocean/net/server/unix/UnixListener.d
Labels: type-bug
