Repository sociomantic-tsunami/ocean, pull requests merged in 2019-03, with the labels that each got.

#682 Fix Import
  src/ocean/io/select/protocol/generic/ErrnoIOException.d
Labels: type-bug

#680 Resolve infinite loop on a Cache clear
  src/ocean/util/container/cache/model/containers/KeyToNode.d
Labels: type-bug

#684 Add a cli arguments parser for date intervals
  relnotes/timeintervalargs.feature.md
  src/ocean/text/arguments/TimeIntervalArgs.d
Labels: type-feature

#689 Start using package.d feature
  relnotes/package.breaking.md
  src/ocean/meta/traits/package.d
  src/ocean/meta/types/package.d
  src/ocean/task/extensions/package.d
  src/ocean/util/container/cache/CachingStructLoader.d
  src/ocean/util/container/cache/CachingStructLoader_test.d
  src/ocean/util/container/cache/ExpiredCacheReloader.d
  src/ocean/util/container/cache/ExpiredCacheReloader_test.d
  src/ocean/util/serialize/contiguous/package.d
  src/ocean/util/serialize/package.d
Labels: type-breaking

#687 Drop wchar/dchar support from ocean.text.Util
  relnotes/text.breaking.md
  src/ocean/text/Search.d
  src/ocean/text/Util.d
  src/ocean/text/convert/TimeStamp.d
  src/ocean/text/json/Json.d
Labels: type-breaking
